name: 'CMake Linux'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  # Note: [GHA Default environment variables](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)

  Linux:
    name: Ubuntu Linux ${{ matrix.cmake.configure_preset }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:                  [ ubuntu-24.04 ]
        os:                     [ linux ]
        cmake:
        - {
            cxx:                "g++",
            configure_preset:   "gcc",
            build_preset:       "gcc-release",
          }
        - {
            cxx:                "clang++",
            configure_preset:   "clang",
            build_preset:       "clang-release",
          }
        - {
            cxx:                "clang++",
            configure_preset:   "clang-libc++",
            build_preset:       "clang-libc++-release",
            depend_pkgs:        "libc++-dev"
          }

    steps:

    - name: Trigger event
      run: |
        echo "Triggered by ${{ github.event_name }}"

    - name: Install required build dependencies on ${{ matrix.image }}
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
      if: startsWith(matrix.image, 'ubuntu')
      # fail-safe check - only Ubuntu this days
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          cmake ninja-build ccache g++ clang "${{ matrix.cmake.depend_pkgs }}"

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set Github runner's env (CXX=${{ matrix.cmake.cxx }})
      run: |
        echo "CXX=${{ matrix.cmake.cxx }}" >> $GITHUB_ENV

    - name: Check prerequisites
      run: |
        eval ${CXX} --version
        cmake --version
    
    - name: CMake configuration
      run: |
        cmake --list-presets
        cmake --preset ${{ matrix.cmake.configure_preset }}

    - name: CMake build
      run: |
        cmake --build --preset ${{ matrix.cmake.build_preset }}
